<?php
/**
 * PutlerConnector
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.

 * @category    Putler Mod
 * @package     Putler_PutlerConnector
 * @author      Putler Core Team
 * @copyright   Copyright (c) 2012 Atwix (http://www.putler.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<script type="text/javascript">
	    //<![CDATA[
	    function check() {
		    var email = document.getElementById('putlersettings_general_putler_email').value;
		    var api_token = document.getElementById('putlersettings_general_putler_api_token').value;
	        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
	            method: 'get',
	            parameters: {email: email, api_token: api_token},
	            dataType: 'json', 
	            onSuccess: function(response){
		            if (response.responseJSON.ACK == 'SUCCESS'){
		                alert(response.responseJSON.MESSAGE);
		            } else {
		            	alert(response.responseJSON.MESSAGE);
		            }
	            }
	        });
	    }
	    //]]>
</script>

<?php echo $this->getButtonHtml() ?>
